# Generated by Django 3.2.7 on 2021-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firebaseusers',
            options={'verbose_name': 'Firebase Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='create_at',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='last_sign_in',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='provider',
            field=models.CharField(default='Email/Phone', max_length=50),
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='user_image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='firebaseusers',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firebaseusers',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='firebaseusers',
            name='username',
            field=models.CharField(default='Guest User', max_length=50),
        ),
    ]
