# Generated by Django 3.2.7 on 2021-09-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210912_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseusers',
            name='last_sign_in',
            field=models.CharField(default='', max_length=100),
        ),
    ]
