# Generated by Django 3.2.7 on 2021-09-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210913_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseusers',
            name='phone',
        ),
    ]
