# Generated by Django 3.2.7 on 2021-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_firebaseusers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseusers',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
