# Generated by Django 3.2.7 on 2021-09-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210914_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseusers',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=100),
        ),
    ]
