# Generated by Django 3.2.7 on 2021-09-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_firebaseusers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebaseusers',
            old_name='username',
            new_name='name',
        ),
    ]
