# Generated by Django 3.2.7 on 2021-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_username_firebaseusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebaseusers',
            name='create_at',
            field=models.DateTimeField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='firebaseusers',
            name='last_sign_in',
            field=models.DateTimeField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='firebaseusers',
            name='provider',
            field=models.CharField(blank=True, default='Password', max_length=50),
        ),
    ]
