# Generated by Django 3.2.7 on 2021-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dummymodel',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
