# Generated by Django 3.2.7 on 2021-09-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firestore', '0004_alter_dummymodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummymodel',
            name='user',
        ),
    ]
