# Generated by Django 3.2.7 on 2021-09-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210915_1613'),
        ('firestore', '0005_remove_dummymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firestore_user', to='users.firebaseusers'),
        ),
    ]
