# Generated by Django 3.2.7 on 2021-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210915_1613'),
        ('firestore', '0006_dummymodel_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummymodel',
            name='user1',
        ),
        migrations.AddField(
            model_name='dummymodel',
            name='user1',
            field=models.ManyToManyField(blank=True, null=True, related_name='firestore_user', to='users.FirebaseUsers'),
        ),
    ]
